export const RULES = [
    { id: 1, package: 'eslint', ruleName: 'import/no-extraneous-dependencies', description: 'Disallow unnecessary dependencies in import statements.', enabled: false, level: 'off' },
    { id: 2, package: 'eslint', ruleName: 'react/react-in-jsx-scope', description: 'React must be in scope when using JSX.', enabled: false, level: 'off' },
    { id: 3, package: 'eslint', ruleName: 'react/jsx-filename-extension', description: 'Restrict file extensions that may contain JSX.', enabled: false, level: 'off' },
    { id: 4, package: 'eslint', ruleName: 'import/named', description: 'Ensure named imports correspond to a named export in the remote file.', enabled: false, level: 'off' },
    { id: 5, package: 'eslint', ruleName: 'import/extensions', description: 'Ensure consistent use of file extension within import paths.', enabled: false, level: 'off' },
    { id: 6, package: 'eslint', ruleName: 'import/no-unresolved', description: 'Ensure imports point to files/modules that can be resolved.', enabled: false, level: 'off' },
    { id: 7, package: 'eslint', ruleName: 'no-continue', description: 'Disallow use of continue statement.', enabled: false, level: 'off' },
    { id: 8, package: 'eslint', ruleName: 'import/no-import-module-exports', description: 'Prevent mixing import and module.exports.', enabled: false, level: 'off' },
    { id: 9, package: 'eslint', ruleName: 'no-shadow', description: 'Disallow variable declarations from shadowing variables in the outer scope.', enabled: false, level: 'off' },
    { id: 10, package: 'eslint', ruleName: '@typescript-eslint/no-shadow', description: 'Disallow variable declarations from shadowing variables declared in the outer scope in TypeScript.', enabled: false, level: 'error' },
    { id: 11, package: 'eslint', ruleName: 'no-unused-vars', description: 'Disallow unused variables.', enabled: false, level: 'warn' },
    { id: 12, package: 'eslint', ruleName: 'react/no-unused-prop-types', description: 'Prevent definitions of unused prop types.', enabled: false, level: 'warn' },
    { id: 13, package: 'eslint', ruleName: '@typescript-eslint/no-unused-vars', description: 'Disallow unused variables in TypeScript.', enabled: false, level: 'warn' },
    { id: 14, package: 'eslint', ruleName: 'react/function-component-definition', description: 'Enforce a specific function type for function components.', enabled: false, level: 'error' },
    { id: 15, package: 'eslint', ruleName: 'import/prefer-default-export', description: 'Prefer default export if module exports a single name.', enabled: false, level: 'off' },
    { id: 16, package: 'eslint', ruleName: 'react/jsx-no-useless-fragment', description: 'Disallow unnecessary fragments.', enabled: false, level: 'warn' },
    { id: 17, package: 'eslint', ruleName: 'no-useless-escape', description: 'Disallow unnecessary escape usage.', enabled: false, level: 'warn' },
    { id: 18, package: 'eslint', ruleName: 'react/jsx-props-no-spreading', description: 'Disallow JSX prop spreading.', enabled: false, level: 'warn' },
    { id: 19, package: 'eslint', ruleName: 'jsx-a11y/click-events-have-key-events', description: 'Ensure clickable elements are keyboard accessible.', enabled: false, level: 'off' },
    { id: 20, package: 'eslint', ruleName: 'jsx-a11y/heading-has-content', description: 'Ensure headings have content and are not empty.', enabled: false, level: 'off' },
    { id: 21, package: 'eslint', ruleName: 'class-methods-use-this', description: 'Enforce that class methods utilize `this`.', enabled: false, level: 'off' },
    { id: 22, package: 'eslint', ruleName: 'no-bitwise', description: 'Disallow bitwise operators.', enabled: false, level: 'off' },
    { id: 23, package: 'eslint', ruleName: 'react/jsx-pascal-case', description: 'Enforce PascalCase for user-defined JSX components.', enabled: false, level: 'error' },
    { id: 24, package: 'eslint', ruleName: 'react/jsx-no-script-url', description: 'Disallow using `javascript:` URLs.', enabled: false, level: 'error' },
    { id: 25, package: 'eslint', ruleName: 'react/static-property-placement', description: 'Enforce static class properties placement.', enabled: false, level: 'warn' },
    { id: 26, package: 'eslint', ruleName: 'react/no-typos', description: 'Disallow typos in JSX elements.', enabled: false, level: 'error' },
    { id: 27, package: 'eslint', ruleName: 'react/prefer-stateless-function', description: 'Enforce stateless functional components.', enabled: false, level: 'warn' },
    { id: 28, package: 'eslint', ruleName: 'react/self-closing-comp', description: 'Enforce self-closing tags in JSX.', enabled: false, level: 'warn' },
    { id: 29, package: 'eslint', ruleName: 'quotes', description: 'Enforce the consistent use of single quotes.', enabled: false, level: 'warn' },
    { id: 30, package: 'eslint', ruleName: 'semi', description: 'Require semicolons at the end of statements.', enabled: false, level: 'warn' },
    { id: 31, package: 'eslint', ruleName: 'no-console', description: 'Disallow the use of console statements in production code.', enabled: false, level: 'warn' },
    { id: 32, package: 'eslint', ruleName: 'no-alert', description: 'Disallow the use of alert, confirm, and prompt.', enabled: false, level: 'error' },
    { id: 33, package: 'eslint', ruleName: 'react/no-array-index-key', description: 'Disallow using array index as a key in React components.', enabled: false, level: 'warn' },
    { id: 34, package: 'eslint', ruleName: 'no-debugger', description: 'Disallow the use of debugger.', enabled: false, level: 'warn' },
    { id: 35, package: 'eslint', ruleName: 'no-extra-boolean-cast', description: 'Disallow unnecessary boolean casts.', enabled: false, level: 'warn' },
    { id: 36, package: 'eslint', ruleName: 'eqeqeq', description: 'Require the use of === and !== instead of == and !=.', enabled: false, level: 'error' },
    { id: 37, package: 'eslint', ruleName: 'no-mixed-spaces-and-tabs', description: 'Disallow mixed spaces and tabs for indentation.', enabled: false, level: 'warn' },
    { id: 38, package: 'eslint', ruleName: 'react/jsx-uses-react', description: 'Enforce that React is correctly marked as a dependency in JSX files.', enabled: false, level: 'warn' },
    { id: 39, package: 'eslint', ruleName: 'react/jsx-uses-vars', description: 'Enforce that variables used in JSX are declared.', enabled: false, level: 'warn' },
    { id: 40, package: 'eslint', ruleName: 'react/jsx-no-undef', description: 'Disallow undeclared variables in JSX.', enabled: false, level: 'warn' },
    { id: 41, package: 'eslint', ruleName: 'react/jsx-no-duplicate-props', description: 'Disallow duplicate props in JSX.', enabled: false, level: 'error' },
    { id: 42, package: 'eslint', ruleName: 'react/jsx-no-comment-textnodes', description: 'Disallow comments as a child of JSX nodes.', enabled: false, level: 'error' },
    { id: 43, package: 'eslint', ruleName: 'react/jsx-no-target-blank', description: 'Disallow target="_blank" in JSX.', enabled: false, level: 'error' },
    { id: 44, package: 'eslint', ruleName: 'react/jsx-key', description: 'Enforce that key prop is specified on elements with arrays or iterators.', enabled: false, level: 'error' },
    { id: 45, package: 'eslint', ruleName: 'react/jsx-no-bind', description: 'Disallow function binding in JSX props.', enabled: false, level: 'error' },
    { id: 46, package: 'eslint', ruleName: 'react/no-deprecated', description: 'Avoid deprecated methods in React.', enabled: false, level: 'error' },
    { id: 47, package: 'eslint', ruleName: 'react/boolean-prop-naming', description: 'Enforce consistent naming of boolean props.', enabled: false, level: 'error' },
    { id: 48, package: 'eslint', ruleName: 'import/newline-after-import', description: 'Enforce a newline after import statements.', enabled: false, level: 'warn' },
    { id: 49, package: 'eslint', ruleName: 'import/order', description: 'Enforce a consistent order for import statements.', enabled: false, level: 'warn' },
    { id: 50, package: 'eslint', ruleName: 'no-magic-numbers', description: 'Disallow the use of magic numbers.', enabled: false, level: 'error' },
    { id: 51, package: 'eslint', ruleName: 'camelcase', description: 'Enforce consistent naming of variables, functions, and classes.', enabled: false, level: 'error' },
    { id: 52, package: 'eslint', ruleName: 'arrow-parens', description: 'Require or disallow parentheses around arrow function arguments.', enabled: false, level: 'warn' },
    { id: 53, package: 'eslint', ruleName: 'padding-line-between-statements', description: 'Require or disallow an empty line before return statements.', enabled: false, level: 'warn' },
    { id: 54, package: 'eslint', ruleName: 'radix', description: 'Enforce the consistent use of the radix argument when using parseInt.', enabled: false, level: 'error' },
];
